version: '2'
services:
  node:
    image: node:6.7-onbuild
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '9876:9876'
    command: npm run karma
volumes:
  node_modules:
